name = "prasenjit-shop-api"
main = "worker.js"
compatibility_date = "2024-01-01"

[[d1_databases]]
binding = "DB"
database_name = "prasenjit-shop-api"
database_id = "82a3374e-ff31-4263-b985-1b44adfd645a"
